'use client';

import { useQuery } from '@tanstack/react-query';
import { useMemo } from 'react';
import Link from 'next/link';
import { ArrowRight, Lightbulb } from 'lucide-react';
import { analyticsApi, tasksApi, workflowsApi } from '@/lib/api/endpoints';
import { useWorkspace } from '@/components/dashboard/workspace-provider';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Badge } from '@/components/ui/badge';

/**
 * Rule-based recommendations.
 *
 * These are computed from real workspace data rather than generated by the model
 * — they are cheap, deterministic, and need no AI key, so the dashboard always
 * has something useful to say. Model-backed suggestions appear inside the
 * workflow builder via the improve-workflow endpoint.
 */
type Suggestion = {
  id: string;
  title: string;
  detail: string;
  href: string;
  severity: 'info' | 'warning';
};

export function AiSuggestions() {
  const { activeWorkspace } = useWorkspace();
  const workspaceId = activeWorkspace?.id;

  const metricsQuery = useQuery({
    queryKey: ['analytics', workspaceId, 'metrics'],
    queryFn: () => analyticsApi.metrics(workspaceId!),
    enabled: Boolean(workspaceId),
  });

  const overdueQuery = useQuery({
    queryKey: ['tasks', workspaceId, 'overdue-preview'],
    queryFn: () => tasksApi.list({ workspaceId: workspaceId!, overdue: true, limit: 5 }),
    enabled: Boolean(workspaceId),
  });

  const draftsQuery = useQuery({
    queryKey: ['workflows', workspaceId, 'drafts-preview'],
    queryFn: () => workflowsApi.list({ workspaceId: workspaceId!, status: 'DRAFT', limit: 5 }),
    enabled: Boolean(workspaceId),
  });

  const suggestions = useMemo<Suggestion[]>(() => {
    const metrics = metricsQuery.data?.metrics;
    if (!metrics) return [];

    const out: Suggestion[] = [];

    if (metrics.tasks.overdue > 0) {
      out.push({
        id: 'overdue',
        title: `${metrics.tasks.overdue} task${metrics.tasks.overdue === 1 ? '' : 's'} past due`,
        detail:
          'Overdue work pushes every downstream step. Consider reassigning or moving deadlines.',
        href: `/dashboard/tasks?workspace=${workspaceId}&overdue=true`,
        severity: 'warning',
      });
    }

    const draftCount = draftsQuery.data?.total ?? 0;
    if (draftCount > 0) {
      out.push({
        id: 'drafts',
        title: `${draftCount} workflow${draftCount === 1 ? '' : 's'} still in draft`,
        detail: 'Drafts cannot be executed. Publish the ones that are ready.',
        href: `/dashboard/workflows?workspace=${workspaceId}&status=DRAFT`,
        severity: 'info',
      });
    }

    if (metrics.tasks.total > 0 && metrics.tasks.completionRate < 40) {
      out.push({
        id: 'rate',
        title: `Completion rate is ${Math.round(metrics.tasks.completionRate)}%`,
        detail:
          'A low rate usually means too much work in progress at once, not a slow team.',
        href: `/dashboard/analytics?workspace=${workspaceId}`,
        severity: 'info',
      });
    }

    if (metrics.tasks.total === 0 && metrics.workflows.total > 0) {
      out.push({
        id: 'no-tasks',
        title: 'Workflows have no tasks yet',
        detail: 'Open a workflow and generate tasks from its nodes to start tracking work.',
        href: `/dashboard/workflows?workspace=${workspaceId}`,
        severity: 'info',
      });
    }

    return out.slice(0, 3);
  }, [metricsQuery.data, draftsQuery.data, workspaceId]);

  const loading = metricsQuery.isLoading || draftsQuery.isLoading || overdueQuery.isLoading;

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-sm">
          <Lightbulb className="size-4 text-primary" aria-hidden="true" />
          Suggestions
        </CardTitle>
      </CardHeader>
      <CardContent>
        {loading ? (
          <div className="space-y-3" aria-busy="true">
            {Array.from({ length: 2 }).map((_, index) => (
              <div key={index} className="space-y-1.5">
                <Skeleton className="h-3.5 w-40" />
                <Skeleton className="h-3 w-56" />
              </div>
            ))}
          </div>
        ) : suggestions.length === 0 ? (
          <p className="py-2 text-sm text-muted-foreground">
            Nothing needs attention right now. Overdue tasks and stalled drafts will surface here.
          </p>
        ) : (
          <ul className="space-y-3.5">
            {suggestions.map((suggestion) => (
              <li key={suggestion.id} className="group">
                <div className="flex items-start justify-between gap-2">
                  <p className="text-sm font-medium">{suggestion.title}</p>
                  {suggestion.severity === 'warning' ? (
                    <Badge variant="warning" className="shrink-0">
                      attention
                    </Badge>
                  ) : null}
                </div>
                <p className="mt-0.5 text-xs text-muted-foreground">{suggestion.detail}</p>
                <Link
                  href={suggestion.href}
                  className="mt-1.5 inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline"
                >
                  Review
                  <ArrowRight className="size-3" aria-hidden="true" />
                </Link>
              </li>
            ))}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}
